---
- name: Setup NGINX
  hosts: hexlettask
  become: true
  vars:
    config_source: /home/mememe/yamlpractice/webserver.conf  
    html_source: /home/mememe/yamlpractice/hexlet.html
    nginx_port: 8080
    root_dir: /usr/share/nginx/html/
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Copy html file
    ansible.builtin.template:
      src: "{{ html_source }}"
      dest: "{{ root_dir }}/index.html"
  - name: Copy webserver configuration
    ansible.builtin.template:
      src: "{{ config_source }}"
      dest: /etc/nginx/nginx.conf
    notify:
      - Reload nginx
  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: restarted